### ISSUE TITLE
Impossible to Install and Activate - ERROR

### ISSUE THREAD

**Issue by Eldenroot** [ryczypior/discord-webhook-for-mybb#1]
![image](https://user-images.githubusercontent.com/778890/31677655-d40e52c2-b36b-11e7-82ce-06386d74ba1f.png)

I get this ugly error when I wanna install and activate your plugin. I use PHP 7.0.21 and MyBB 1.8.12

@ryczypior

**Comment by ryczypior** [comment]
I've just push a commit that escapes settings titles, it works now

**Comment by Eldenroot** [comment]
Thank you, I am going to test it :)
