### ISSUE TITLE
Plugin not working after last update.

### ISSUE THREAD

**Issue by RikoDEV** [ryczypior/discord-webhook-for-mybb#12]
Plugin not working after last update. When writing a post forum stop at the loading spinner and information about the new post is not sent to discord server.

Configuration bug on fresh installation:

![bug](https://user-images.githubusercontent.com/18230443/34375316-318a136c-eae6-11e7-95ec-cd903e82db63.PNG)

**Comment by ryczypior** [comment]
I've just fixed the configuration options. It should not stop the plugin, and I thing it was because the part of code for getting avatar url:
```php
$method = 'getAvatarUrl' . ucfirst($avatartype);
if (!method_exists($this, $method)) {
    $method = 'getAvatarUrlDefault';
}
$avatar = $discordWebhook->$method($avatar);
```
I have changed this part to use with older PHP versions.

**Comment by ryczypior** [comment]
@RikoDEV, Is this working for you now?

**Comment by RikoDEV** [comment]
Yes, it working now.
