### ISSUE TITLE
Post new threads - issue on Discord

### ISSUE THREAD

**Issue by Eldenroot** [ryczypior/discord-webhook-for-mybb#14]
I use your latest version from GitHub, everything seems to be fine except posting info about new threads to Discord channel. I use my custom color, but after sending a thread, the info in discord channel is not complete - the color bar with link is missing

![image](https://user-images.githubusercontent.com/778890/34448686-fce4c86c-ecef-11e7-9d89-d426f628086c.png)

I use this settings:
![image](https://user-images.githubusercontent.com/778890/34448695-1c8b6ab8-ecf0-11e7-9156-9e4b422da4a8.png)

**Comment by ryczypior** [comment]
It's because you send only a regular message. Label border shows only if a rich message is sent. Maybe I should add an option to send regular message in rich aggregator?

**Comment by Eldenroot** [comment]
is possible to add label to regular message? If not, please yes add your idea mentioned above :) thank you

**Comment by ryczypior** [comment]
No, it's not possible :/ It needs to be send as a rich message. I'll work on it :)

**Comment by Eldenroot** [comment]
Hi @ryczypior - any progress with that? I would like to make it working :)

**Comment by ryczypior** [comment]
Closed due to #26
