### ISSUE TITLE
add a "userfields"

### ISSUE THREAD

**Issue by dvddvd300** [ryczypior/discord-webhook-for-mybb#15]
add a "userfields" in my case i want to add "fid4" (there I have the discord id of my users (example: User#1234))

**Comment by ryczypior** [comment]
I'll work on that

**Comment by Eldenroot** [comment]
IT should not be added into this plugin, you can create custom profile field via ACP and display in postbit and member profile... or am I missing something?

**Comment by ryczypior** [comment]
I thought @dvddvd300 wanted to use custom fields as a parameters for discord message, for example {fid4} instead of {username}... @dvddvd300 is that correct?

**Comment by ryczypior** [comment]
I've just added an additional userfields to use in message or bot's name
