### ISSUE TITLE
friendly urls

### ISSUE THREAD

**Issue by raymond4400** [ryczypior/discord-webhook-for-mybb#16]
more of a question then an issue. I was wondering if your update for friendly urls will also work with the google seo addon since they are generated differently.

Thanks

**Comment by ryczypior** [comment]
Could you provide me a link to this plugin? I'd like to check this.

**Comment by raymond4400** [comment]
Sure...

https://community.mybb.com/mods.php?action=view&pid=789

**Comment by raymond4400** [comment]
Google seo has been around forever and in earlier versions

**Comment by raymond4400** [comment]
I was going to add this since I updated the forums but didn't want it to break the webhook mod. Any updates on this?

**Comment by ryczypior** [comment]
I'll try to check it and, if it doesn't work, I'll try to adaptate it to work with Google SEO Plugin tomorrow evening (tuesday, 02/13/2018).

**Comment by raymond4400** [comment]
Wow Thanks

**Comment by ryczypior** [comment]
@raymond4400 discord plugin works with Google SEO plugin, since it changes default MyBB functions get_thread_link and get_post_link

**Comment by raymond4400** [comment]
So even though the links change so much it won't matter? Because the links do not even have .html at end of them.  I can try it I guess lol.   Thanks
