### ISSUE TITLE
Create new Thread = HTTP ERROR 500 and no Discord Post

### ISSUE THREAD

**Issue by david-maus** [ryczypior/discord-webhook-for-mybb#17]
Hi,

- Uploaded the inc folder
- Installed / Activated the Plugin
- Generated a Webhook URL and set it up in the Plugins Settings
- Create a new Thread gives:

Chrome Errormessage with:

HTTP ERROR 500

If i go back to the Forum the Thread is created but no Post in Discord.

Any workaround or is something messed up on my side?

Details:
php_7.0.18_x64
nginx_1.13.1_x86
mariadb_10.2.6_x64

MyBB 1.8.14

Best Regards

**Comment by ryczypior** [comment]
Hey,
Do you have curl installed on server?

**Comment by david-maus** [comment]
php_curl.dll is in folder "ext"

"extension=php_curl.dll" - without semicolon is in my php.ini

So, i think.. yeah :)

**Comment by ryczypior** [comment]
You're on windows? Could you provide PHP and/or ngix error.log?

**Comment by david-maus** [comment]
Hi,
sorry but my php.ini was loaded from another installation....(plesk nonsense, but extension was also loaded in this ini). Checked it with phpinfo... Now the HTTP ERROR is gone but there is no discord post. :/

php:
http://gef-gaming.de/phpinfo.php

forum:
http://www.gef-gaming.de/forum/index.php

So, no error on create thread etc. but also no discord post.

**Comment by david-maus** [comment]
Just for the info:
The webhook is this:

********edited*******

I can generate a new later...

**Comment by ryczypior** [comment]
It's weird, could you provide error log? I you don't have any, you can set a path to error logfile to error_log option in your php.ini file

**Comment by david-maus** [comment]
Hm, i have set it to a file but there is no file after restart php and nginx. Maybe there is no error? 
It is like there is no discord webhook plugin. No error message, nothing after thread creation or post an answer.

**Comment by ryczypior** [comment]
Message from discord plugin should be sent if:
1) Plugin is installed and turned on
2) Pushing information about threads/posts is turned on
3) Threads/posts are created in boards set in "Enabled boards" and NOT in "Ignored boards" option
4) User is NOT in group set in "Ignored usergroups" option
Maybe it's connected to the https... Could you run this command your server?
```
curl -H "Content-Type: application/json" -X POST -d '{"username": "test", "content": "test"}' https://discordapp.com/api/webhooks/420520593948016652/hSMuwk1VzL_13WDiPss_mDbTUIhXk09BmZJfxeRCp-ONqiGbursrHY2D16MMDLHyHFVU
```
I've also registered on your forum with username: ryczypior - if nothing will work, could you set  temporary administrator privileges for my account?

**Comment by ryczypior** [comment]
I've just tried to push a test message to your webhook and it gives me:
```{"code": 10015, "message": "Unknown Webhook"}```
The webhook you provided is invalid

**Comment by david-maus** [comment]
Yeah, i had generated a new already :)
You ar admin... feel free to look around

**Comment by ryczypior** [comment]
Could you run curl command from your server with your new webhook?

**Comment by david-maus** [comment]
No, i think the command is for linux with installed curl?
But your testtext is in received in the discord channel.

**Comment by ryczypior** [comment]
Yes, but it could be related to curl/openssl/firewall problem on your server... I'm trying to find any solution for this issue...

**Comment by ryczypior** [comment]
@david-maus could you extract attached zip file and edit the _test_discord.php_ file, edit and change 2 last lines to use your webhook:
```php
test_curl('test bot', 'Test message', 'https://discordapp.com/api/webhooks/');
test_socket('test bot', 'Test message', 'https://discordapp.com/api/webhooks/');
```
upload php file on your server and run it (in browser for example)? It will make a curl and socket test connection to your discord channel and probably you should get an information about some problems
[test_discord.zip](https://github.com/ryczypior/discord-webhook-for-mybb/files/1785156/test_discord.zip)

**Comment by david-maus** [comment]
Ok, here is the link:

http://www.gef-gaming.de/forum/test_discord.php

**Comment by david-maus** [comment]
I have
gef-gaming.de.key
gef-gaming.de.crt

files for nginx under the vhost. (letsencrypt certificate)
Is there an error with the ssl certification?

**Comment by ryczypior** [comment]
That's your certificates. This error is related to discord certs which couldn't be authenticated by cURL's CA certificate.
1. You should download CA cert (see the second answer in SO: https://stackoverflow.com/questions/6400300/https-and-ssl3-get-server-certificatecertificate-verify-failed-ca-is-ok)
2. If above doesn't work, could you change these lines:
```php
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
```
to
```php
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
```
and run the test again?
3. If the method above doesn't work could you comment test_curl line?
```php
//test_curl('test bot', 'Test message', 'https://discordapp.com/api/webhooks/');
```
and run only the socket test?

**Comment by david-maus** [comment]
Oh man

Number 1. second answer is working.

I have 2 messages now in discord and this is the output:

Performing cURL test...
Performing socket test...

Notice: Undefined variable: ret in C:\_SERVER\WAMP\sites\gef-gaming.de\forum\test_discord.php on line 48

Errno: 0
Errmsg:

**Comment by david-maus** [comment]
Your plugin is now working (Tested a forum post)!

Thank you for all the help today...... :)

I think its now all correct?

**Comment by ryczypior** [comment]
Great :) I've just changed your discord config to show full information (I've set this to "only info message before for testing)
It should works ok, If you want, make your own messages or change other options in your configuration :)
Also, remove me from the administrators group, and... enjoy! :D

**Comment by david-maus** [comment]
Ok :D 

Many many many thanks.... have a nice day :)
