### ISSUE TITLE
Error when unregisterd user Posts.

### ISSUE THREAD

**Issue by 2beFlo** [ryczypior/discord-webhook-for-mybb#18]
Hey there,

great plugin, but it seems that its not really build for using in parts of the forum where unregisterd users can post. allways keep getting an php-error on the load page. 

Unfortunatly I could not copy that error due to fast realod times, but it seems easy to recreate. Maybe you can fix that.

**Comment by ryczypior** [comment]
That's right, it's looking for a registered users, I'll fix that asap (probably saturday)!

**Comment by 2beFlo** [comment]
Wow, thats fast! Thanks a lot!

**Comment by ryczypior** [comment]
It should works now, @2beFlo please check if it's ok for you.

**Comment by 2beFlo** [comment]
It does work perfect! Thanks a lot! :)

**Comment by ryczypior** [comment]
Great! Thanks!
