### ISSUE TITLE
Add option to enable only for new threads/posts or both

### ISSUE THREAD

**Issue by Eldenroot** [ryczypior/discord-webhook-for-mybb#2]
Now we cannot sellect only to post info about new threads... there should be a settings for that.

**Comment by ryczypior** [comment]
Of course, you're right and it will be soon

**Comment by ryczypior** [comment]
I've added setting to select what info should be pushed. You need to uninstall and reinstall plugin

**Comment by Eldenroot** [comment]
Thank you, updated to your last version! Keep good work!
