### ISSUE TITLE
replying to a thread

### ISSUE THREAD

**Issue by RexEtImperator** [ryczypior/discord-webhook-for-mybb#20]
Fatal error: Call to undefined function curl_strerror() in C:\xampp\htdocs\forum1.0\inc\plugins\discord_webhooks\DiscordWebhook.php on line 62

**Comment by ryczypior** [comment]
It seems you have php in version below 5.5. Have you tried to use sockets instead of cURL?

**Comment by RexEtImperator** [comment]
PHP Version 5.4.7, tak/yes

**Comment by RexEtImperator** [comment]
when i reload page xampp takes lag

**Comment by ryczypior** [comment]
Spróbuj w ustawieniach pluginu ustawić użycie sockets zamiast cURL - funkcja curl_strerror pojawiła się dopiero w php 5.5
Try to set sockets instead of cURL in plugin settings - curl_strerror function appeared in php since 5.5 version
