### ISSUE TITLE
Portions of the URL are missing

### ISSUE THREAD

**Issue by SwankyNoodle** [ryczypior/discord-webhook-for-mybb#22]
We have been using this plugin for nearly a year now and have only recently started to run into this issue. The message posted will be all correct except it will be missing the thread number. This only happens every so often so it makes it harder to track down weather its an issue with the plugin or our site. 

Example of a broken message:

`AUTHOR NAME has posted a new thread to the forums: THREAD TITLE  http://example.com/thread-.html`

Note the missing thread number, this only started happening lately when we reached over ~800 threads on the forums. Is this an issue with the plugin? I have the settings set to not using sockets.

Plugin version: 1.11
MyBB version: 1.8.14

**Comment by ryczypior** [comment]
@SwankyNoodle Could you provide your plugin list?

**Comment by SwankyNoodle** [comment]
The following are the enabled plugins I run. The name, version and author is listed:

- Discord Webhooks for MyBB (1.11) -- Ryczypiór
- Extended Polls (Pollmanager) (1.5.3) -- juventiner
- Private Message Log (1.3) -- Starpaul20
- Staff Page (1.0) -- mrnu
- Stop Forum Spam (1.4) -- Tim B. and Tomm
- View Unread Posts (1.8) -- Lukasz Tkacz
- Upcoming Events (1.1) -- Starpaul20

**Comment by ryczypior** [comment]
It shouldn't be connected with number of threads. Did you notice same thing for posts (if you use post pushing of course).
It looks like you're using google seo plugin (url scheme), do you?
I'll need some time to check what's wrong.

**Comment by ryczypior** [comment]
Ok, I've got it :D When the user first save thread as a draft, and then publish it, it seems that the URL isn't creating properly. I'll check if it's not a MyBB issue and if I can do something with that

**Comment by ryczypior** [comment]
It should works now, could you update the plugin and check it for couple a days?
