### ISSUE TITLE
Add a new option - post info about new user registrations

### ISSUE THREAD

**Issue by Eldenroot** [ryczypior/discord-webhook-for-mybb#24]
Would be nice to add an option to send to Discord channel info where a new user is registered.

- username
- avatar
- time/date
- select usergroup - I mean post info only when user will be for example activated not just registered (or where - is that even possible?
- add a color for this kind of messages

**Comment by ryczypior** [comment]
When user has been just registered he can't add the avatar. I've added an information about user registration, please check if it's relevant for you.

**Comment by Eldenroot** [comment]
Thank you, I will on monday, not home atm

**Comment by Eldenroot** [comment]
Great, really nice, thank you!
