### ISSUE TITLE
Color picker is not working for the colored bar in Discord messages/threads

### ISSUE THREAD

**Issue by Eldenroot** [ryczypior/discord-webhook-for-mybb#26]
Color picker is not working for the colored bar in Discord messages/threads

- all messages havae teh "grey" left border, even I set different color (for rich messages only tested). This was working maybe in December before you changed...

**Comment by ryczypior** [comment]
I've just tested this and it's still working...

**Comment by ryczypior** [comment]
@Eldenroot does other embed fields (like an avatar) works? Is this bar always gray (for threads and posts)? Does the color is prepended by '#' char?

**Comment by Eldenroot** [comment]
Yes :(

**Comment by ryczypior** [comment]
![przechwycenie obrazu ekranu_2018-04-23_19-43-34](https://user-images.githubusercontent.com/15202406/39143894-744bb1ec-472f-11e8-8a3a-fb7650ab7085.png)
My *New post label color* value is #FF0000, and *New thread label color* value is #00AA00... I've been trying do uninstall and reinstall again and it all works...

**Comment by Eldenroot** [comment]
Did you try rich message? Or post a thread?

**Comment by ryczypior** [comment]
Long and short rich message, Only Info option won't show a bar at all
Works with posts and threads, but only for rich message

**Comment by Eldenroot** [comment]
Strange, I will try to debug this... btw is there any way to add support for info option at all?

**Comment by ryczypior** [comment]
Only if info will be sent as a rich message, see Issue #14

**Comment by ryczypior** [comment]
@Eldenroot, could you provide more info about that?

**Comment by Eldenroot** [comment]
@ryczypior - ok, but in the early version of your plugin it was possible even in "simple" mode

**Comment by ryczypior** [comment]
@Eldenroot - As I remember support for labels has been added with fix to issue #5 and it always concerns rich message only and labels has been always applied to rich message section only. In current version it should works with all types but no "Only info message" type. Currently you can use "Only info message as a rich text" type to move your info text to rich message section.

**Comment by Eldenroot** [comment]
Seems to be fine, I am closing this one... if anything I will let you know, thank you!
