### ISSUE TITLE
Request: Sort by Prefix

### ISSUE THREAD

**Issue by FireDitto** [ryczypior/discord-webhook-for-mybb#27]
This is amazing. Good work!

I was wondering, would it be possible in the future to push threads based on Prefix? For example, if someone posts a thread using Prefix A, in any approved board, it will post to the Discord. But if the thread doesn't have Prefix A, it won't post to the Discord?

Similar to how you can ignore usergroups or forums!

'cause that would be insanely useful!

Thanks for sharing this!

**Comment by ThistleProse** [comment]
** Sorry, posted with my old account xD

**Comment by ryczypior** [comment]
@ThistleProse please check new release. If you want to filter postsa and threads by prefix you have to insert their names comma separated into the proper field

**Comment by Eldenroot** [comment]
Just tested, really great and useful addition :)
