### ISSUE TITLE
Followed instructions, not posting on discord, no errors.

### ISSUE THREAD

**Issue by kobe083** [ryczypior/discord-webhook-for-mybb#29]
I have followed the instructions a while ago, and nothing happened. I installed the update, plugged in the webhook, set the forums to include, set it to ignore none. I haven't changed any customizations or anything. When I post a new thread, it does not post on discord. I get no error, no indication as to what is going wrong here. I am using an older theme that I customized and spent a lot of time getting to work on 1.8, I think it was from 1.6 if I remember correctly. I dont know if that matters, some of the templates had to be reset to the original. Help?

**Comment by ryczypior** [comment]
It may be a problem with curl_strerror function which has been announced in php 5.5 (if you have a curl installed ofc). Please set "Use sockets" option to yes and try again. If this won't work, try to comment lines: 50-71, 99, 101-103 in inc/discord_webhooks/DiscordWebhook.php file. Please inform me if it will work for you.

**Comment by kobe083** [comment]
Wow, thank you for the fast reply! And commenting out those lines seems to have worked, thank you very much.

**Comment by ryczypior** [comment]
Glad to hear that :D
