### ISSUE TITLE
Add ignored forums, maybe it is easier than select everything :)

### ISSUE THREAD

**Issue by Eldenroot** [ryczypior/discord-webhook-for-mybb#3]

**Comment by ryczypior** [comment]
It depends who will use it :) I'd rather stay with option to select connected boards. Maybe two options - enabled boards and ignored boards which both have implication to show? I'm open for discussion :D

**Comment by Eldenroot** [comment]
Is possible to add both?

**Comment by ryczypior** [comment]
I'm pretty sure it is :) But I'll check it tomorrow

**Comment by ryczypior** [comment]
I've added ignored boards option, for now plugin should push info from boards selected in Enabled Boards and not from Ignored Boards

**Comment by Eldenroot** [comment]
Great, thank you very much!
