### ISSUE TITLE
Cannot Install Multi

### ISSUE THREAD

**Issue by ThistleProse** [ryczypior/discord-webhook-for-mybb#30]
"Install & Activate" results in;
This page isn’t working
[WEBSITE] is currently unable to handle this request.
HTTP ERROR 500

I am unsure how to fix this?

Thank you!

EDIT TO ADD:
... Ummm....

https://i.gyazo.com/1741d754ac3101a8be799930c71d94d7.png

Why are htey all here? I removed the files for the additionals from the FTP?

**Comment by ryczypior** [comment]
I have to update multiinstance version, it will be ready for next 2-3 hours. 
About these multiple settings - it's because install failure, you can get rid of them by removing sections from {prefix}_settinggroups table and options from {prefix}_settings

**Comment by ryczypior** [comment]
Should be ok now
