### ISSUE TITLE
Plugin colliding with another plugin?

### ISSUE THREAD

**Issue by 0xB9** [ryczypior/discord-webhook-for-mybb#31]
I just uploaded this plugin on my forum and when I go to activate the plugin in the ACP I get the following error.

`Warning [2] require_once(/home/hackrall/public_html/inc/plugins/naoardonate/paymentgateways/.php): failed to open stream: No such file or directory - Line: 46 - File: inc/plugins/naoardonate/loader.php PHP 7.0.30 (Linux)`

`Fatal error: require_once(): Failed opening required '/home/hackrall/public_html/inc/plugins/naoardonate/paymentgateways/.php' (include_path='.:/usr/local/php70/pear') in /home/hackrall/public_html/inc/plugins/naoardonate/loader.php on line 46`

![screenshot-2018-6-11 plugins](https://user-images.githubusercontent.com/33612375/41253222-a9afad96-6d8d-11e8-9cc3-ca18ecff7ab1.png)

The other plugin is [CoderMe Donation](https://community.mybb.com/mods.php?action=view&pid=1039). If I remove the `inc/plugins/discord_webhooks.php` file everything is back to normal...

![screenshot-2018-6-11 plugins 1](https://user-images.githubusercontent.com/33612375/41253457-6605261a-6d8e-11e8-8a68-bf60d316f513.png)

**Comment by ryczypior** [comment]
I'll check compatibility with these plugins

**Comment by ryczypior** [comment]
@0xB9 I've just checked the free version and it works fine. I am sorry, I will not spent 19 EUR just for checking the compatibility with the GOLD version. Maybe you can just update this plugin? In free version there is no inc/plugins/naoardonate/loader.php file, maybe it uses some kind of autoloader function, Maybe if you're using non-mulitinstance version try to remove these lines from /inc/plugins/discord_webhooks/DiscordWebhook.php:
```php
        static public function __callStatic($name, $arguments) {
            $reflection = new ReflectionClass('DiscordWebhook');
            $staticMethods = $reflection->getMethods(ReflectionMethod::IS_STATIC | ReflectionMethod::IS_PUBLIC);
            foreach ($staticMethods as $method) {
                $staticMethod = $method->getName();
                if (preg_match('/^' . preg_quote($staticMethod, '/') . '(.*)$/', $name, $o) > 0) {
                    self::$staticMethod($arguments[0], $o[1]);
                    break;
                }
            }
        }
```
Anyway, I'll try to make contact with the author of the CoderMe Donation plugin, maybe we'll resolve this together.

**Comment by coderme** [comment]
## The problem
**CoderMe Donation GOLD** loader tries to autoload  one of **discord-webhook-for-mybb** classes but fails,

## Quick fix
Replace '**_require_once_**' with '**_include_once_**' in **inc/plugins/naoardonate/loader.php**

**Comment by ryczypior** [comment]
@codermeorg Thank you for your reply! Quick fix should do the job until it will be fixed in the plugin code.
