### ISSUE TITLE
[1.8.19] cURL errors on user registration

### ISSUE THREAD

**Issue by trinitrotoluene** [ryczypior/discord-webhook-for-mybb#33]
When the plugin is enabled, 3 errors are thrown which cause the server to return 500 whenever a new user registers.

```
Type: 2
File: inc/functions.php (Line no. 7066)
Message
Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' (this will throw an Error in a future version of PHP) 
```
```
Type: 2
File: inc/functions.php (Line no. 7064)
Message
Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' (this will throw an Error in a future version of PHP) 
```
```
Type: 2
File: inc/functions.php (Line no. 7063)
Message
Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' (this will throw an Error in a future version of PHP) 
```
Error source in functions.php
```php
if(function_exists("curl_init"))
        {
                $fetch_header = $max_redirects > 0;

                $ch = curl_init();

                $curlopt = array(
                        CURLOPT_URL => $url,
                        CURLOPT_HEADER => $fetch_header,
                        CURLOPT_TIMEOUT => 10,
                        CURLOPT_RETURNTRANSFER => 1,
                        CURLOPT_FOLLOWLOCATION => 0,
                );
```
I'm not entirely sure whether this is an issue with the plugin itself, or a problem with myBB, but I thought I'd flag it up here since it's the plugin causing the error. 

Thanks very much for this, by the way- it's enormously useful.

**Comment by ryczypior** [comment]
Try to comment line 23 in discord_webhooks/DiscordWebhook.php:

`//require_once __DIR__ . '/curl_checker.php';`

I assume your server doesn't have a curl module installed.

**Comment by trinitrotoluene** [comment]
Thanks, this fixes the error! 

However I just wanted to add that regarding the module, the server is running the latest version of cURL and has the extension enabled also.

Have a great evening.
