### ISSUE TITLE
Not works

### ISSUE THREAD

**Issue by berkay97** [ryczypior/discord-webhook-for-mybb#38]
Hello,

I did everything right but still i cant see anything new from our forum. Its like plugin not works. Tried socket / curl too but no way. PHP 7.4 with all needed modules is active and im sure about my discord webhook url is correct

**Comment by ThistleProse** [comment]
https://github.com/ryczypior/discord-webhook-for-mybb/pull/40/files

This edit worked for me! :)

**Comment by berkay97** [comment]
> https://github.com/ryczypior/discord-webhook-for-mybb/pull/40/files
> 
> This edit worked for me! :)

hey,

i edited & replaced but still same, no way.
