### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by raymond4400** [ryczypior/discord-webhook-for-mybb#9]
Doesn't seem to work for me. Added webhook correctly, not sure why. Anything else required?

**Comment by RikoDEV** [comment]
Instalation:
In this section you also need to **specify** which forum threads and posts are being sent to the Discord Webhook

and

Requirements:

- MyBB 1.8+
- curl - for HTTP requests to Discord
- Multibyte String (mb_* string) for multibyte string manipulation

**Comment by ryczypior** [comment]
Like RikoDEV has mentioned, you have to specify from which forum boards the threads and posts will be pushed to Discord WebHook. If you still have a problem with running this plugin, please open new issue and provide more info.
